# Generated by Django 2.1.7 on 2019-03-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mycustomuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='mycustomuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mycustomuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mycustomuser',
            name='user_permissions',
        ),
    ]
