# Generated by Django 2.1.7 on 2019-03-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_auto_20190323_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
