# Generated by Django 2.1.7 on 2019-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
